# Generated by Django 5.0.2 on 2024-02-23 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_usermessage'),
        ('spaceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='missions.missions'),
        ),
    ]
